#pragma once

// Generated by scripts from setup.bat
#include <commit_hash.h>

#define SPTF_NAME            "Spotify Integration"
#define SPTF_UNDERSCORE_NAME "foo_spotify"
#define SPTF_DLL_NAME        SPTF_UNDERSCORE_NAME ".dll"

#define SPTF_STRINGIFY_HELPER( x ) #x
#define SPTF_STRINGIFY( x )        SPTF_STRINGIFY_HELPER( x )

#define SPTF_VERSION_MAJOR           0
#define SPTF_VERSION_MINOR           1
#define SPTF_VERSION_PATCH           0
#define SPTF_VERSION_PRERELEASE_TEXT "beta"

#ifdef SPTF_VERSION_PRERELEASE_TEXT
#    define SPTF_VERSION_PRERELEASE "-" SPTF_VERSION_PRERELEASE_TEXT
#    define SPTF_VERSION_METADATA   "+" SPTF_STRINGIFY( SPTF_COMMIT_HASH )
#else
#    define SPTF_VERSION_PRERELEASE ""
#    define SPTF_VERSION_METADATA   ""
#endif

#ifdef _DEBUG
#    define SPTF_VERSION_DEBUG_SUFFIX " (Debug)"
#else
#    define SPTF_VERSION_DEBUG_SUFFIX ""
#endif

#define SPTF_VERSION                                                                  \
    SPTF_STRINGIFY( SPTF_VERSION_MAJOR )                                              \
    "." SPTF_STRINGIFY( SPTF_VERSION_MINOR ) "." SPTF_STRINGIFY( SPTF_VERSION_PATCH ) \
        SPTF_VERSION_PRERELEASE SPTF_VERSION_METADATA
#define SPTF_NAME_WITH_VERSION SPTF_NAME " v" SPTF_VERSION SPTF_VERSION_DEBUG_SUFFIX

#define SPTF_ABOUT \
    SPTF_NAME_WITH_VERSION " by TheQwertiest"